#!/bin/bash

### CONFIG ###
BN_EDITOR=vim
BN_DIR="/home/$(whoami)/notes"
BN_FILE_FORMAT="md"

# Turns 'word1 word2' to 'word1\ word2'
function escape_spaces {
	#echo "$*" | sed -e s/' '/'\\ '/g
	string="$*"
	echo "${string/ /\\ }"
} 

# Turns 'word' to '*w*o*r*d*'
function joinstr { 
	output="*"
	foo="$*"
	for (( i=0; i<${#foo}; i++ )); do
  	output=${output}"${foo:${i}:1}*"
	done
	echo "$output"
}

# Added just to change message once instead of searching all occurences
function no_file_msg (){
	echo "Ooops there is no $*"
}

# Create folder, if it doesnt exist
function init() {
	mkdir -p "$BN_DIR"
}

function main() {

init

case $1 in 

# Without args just print help 
"")
printf %s "\
	bloknot - a simple script to manage your plain text notes.

	bn [option] [args] or
	bn [note name]

	Options
	=> [r]emove [name] - Delete note.
	=> [s]earch [string] - List notes containing letters from [string] in name. Case insensitive
	=> [g]rep [text] - List notes containing [text]. Case insensitive
	=> [name] - Open/create note with that name. Names can contain whitespaces

"
;;

# Remove the note
# Maybe someday i'll add trashcan for this, but for now it's just simple rm
"r")
shift
FILE_PATH="$BN_DIR/$*.$BN_FILE_FORMAT"
if [ -f "$FILE_PATH" ]; then
	rm "$FILE_PATH"
else
	no_file_msg "$*.$BN_FILE_FORMAT"
fi
;;

# S stands for search. Search notes by name. We make the pattern from 
# args and then find it. Case insensitive.
# That makes something like fuzzy search.
# I believe there is much more effective way to do this.
# Any recommendation are appreciated

"s")
shift
query=$(tr -d ' ' <<< "$*")
find "$BN_DIR" -maxdepth 1 -type f -iname "$(joinstr "${query}")" -exec basename {} .$BN_FILE_FORMAT ';'
;;

# Just a normal case insensitive grep here
# Again, there are probably more effective ways to do this.
"g")
shift
grep -li -e "$*" "$BN_DIR"/*  | while read -r line ; do
	basename "$line" .$BN_FILE_FORMAT
	done
;;

# Other arguements treated as note name,
# so we just open it in $BN_EDITOR
*)
file="$BN_DIR"/"$(escape_spaces "$*")".$BN_FILE_FORMAT
bash -c "${BN_EDITOR} ${file}"
;;

esac
}

main "$@"
